### ISSUE TITLE
Takeover maintenance

### ISSUE THREAD

**Issue by kmdavis** [Nevon/less-terrible-coffeelint-loader#3]
I can take over maintenance of this project, either from this repo, or from my fork (handshake/less-terrible-coffeelint-loader)

My npm username is `kmdavis`

**Comment by Nevon** [comment]
Thank you for offering. I've added you as an owner of the npm package and added you as a collaborator on this repo. In the long run, I would prefer that your fork becomes the "official" repository, so that I can close this one. That would mean that you would update the repository link in the package.json in your fork, pointing to your repo, and then publish a new version of the package. Does that sound okay with you?

**Comment by kmdavis** [comment]
Yeah, that'll work. I'll take care of that tomorrow

**Comment by kmdavis** [comment]
Done
